# Set update schedule for GitHub Actions

version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: ":construction_worker:"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"      
    commit-message:
      prefix: ":arrow_up:"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"            
    commit-message:
      prefix: ":arrow_up:"
    open-pull-requests-limit: 10
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: ":construction_worker:"